name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build and Publish
      run: dotnet publish ArrhythmicBattles --configuration Release --self-contained true --os win --arch x64 -p:PublishSingleFile=true -p:PublishReadyToRun=true -p:PublishTrimmed=true
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: ArrhythmicBattles/bin/Release/net6.0
